version: '3'

services:
  web:
    container_name: shoppingcar
    restart: always
    build: .
    ports:
        - "4000:4000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongoDb
    image: mongo
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: "pass-root"
     MONGO_INITDB_DATABASE: "shoppingCarDB"
    ports:
      - "27017:27017"
    volumes:
     - ~/mongo/data:/data/db
  redis:
    container_name: redisDb
    image: 'redis:alpine'
    ports:
      - "6379:6379"
