# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install 
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git pull
        uses: actions/checkout@v2
      
      - name: PWD
       
        env:
          AWS_EC2_KEY: ${{ secrets.AWS_EC2_PEM  }}
          AWS_EC2_PUBLIC_IP: ${{ secrets.AWS_EC2_PUBLIC_IP  }}
          AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME  }}
        run: | 
          echo "paso 01"
          pwd
          echo "$AWS_EC2_KEY" > private_key && chmod 600 private_key
          ls
          ssh -o StrictHostKeyChecking=no -i private_key $AWS_EC2_USERNAME@$AWS_EC2_PUBLIC_IP '
            cd /var/www/shopping-car-api
            echo "paso 1" 
            sudo git checkout development
            echo "paso 2" 
            sudo git pull origin development
            echo "paso 3"
            sudo docker-compose down
            echo "paso 4" 
            sudo docker-compose up --build --force-recreate -d
          '
